// Generated by https://quicktype.io

export interface TypeFull {
    damage_relations:      DamageRelations;
    generation:            Generation;
    id:                    number;
    move_damage_class:     Generation;
    moves:                 Generation[];
    name:                  string;
    names:                 Name[];
    past_damage_relations: any[];
    pokemon:               Pokemon[];
}

export interface DamageRelations {
    double_damage_from: Generation[];
    double_damage_to:   any[];
    half_damage_from:   any[];
    half_damage_to:     Generation[];
    no_damage_from:     Generation[];
    no_damage_to:       Generation[];
}

export interface Generation {
    name: string;
    url:  string;
}

export interface Name {
    name:     string;
}

export interface Pokemon {
    pokemon: PokemonPokemon;
    slot:    number;
}

export interface PokemonPokemon {
    name: string;
    url:  string;
}
