// Generated by https://quicktype.io

export interface TypeFull {
    damage_relations:      DamageRelations;
    generation:            string;
    id:                    number;
    move_damage_class:     string;
    moves:                 string[];
    name:                  string;
    names:                 Name[];
    past_damage_relations: any[];
    pokemon:               Pokemon[];
}

export interface DamageRelations {
    double_damage_from: string[];
    double_damage_to:   any[];
    half_damage_from:   any[];
    half_damage_to:     string[];
    no_damage_from:     string[];
    no_damage_to:       string[];
}

export interface double_damage_from {
    name: string;
    url:  string;
}

export interface Name {
    name:     string;
}

export interface Pokemon {
    pokemon: PokemonPokemon;
    slot:    number;
}

export interface PokemonPokemon {
    name: string;
    url:  string;
}

export interface Example {    
        key: string,
        name: string,
        role: string,
        status: string,
}