// Generated by https://quicktype.io

export interface TypesList {
    count:    number;
    next:     null;
    previous: null;
    results:  Types[];
}

export interface Types {
    name: string;
    url:  string;
}
